- name: Build and deploy nodes
  hosts: all
  become: yes

  tasks:
  - name: Tear down existing services
    command:
      cmd: >
        docker-compose
        -f {{ workdir}}/{{ docker_compose_file }}
        down


  - name: Delete project directory
    file:
      path: "{{ workdir }}"
      state: absent
      
      
