- name: Restart nodes
  hosts: all
  become: yes

  tasks:
  - name: Stop services
    command:
      cmd: >
        docker-compose
        -f {{ workdir }}/{{ docker_compose_file }}
        stop

  - name: Start services
    command:
      cmd: >
        docker-compose
        -f {{ workdir }}/{{ docker_compose_file }}
        start