- name: Setup server configurations
  hosts: zabbix_server
  become: yes

  tasks:
    - name: Set config
      template: 
        src: ../templates/.env.server.j2
        dest: "{{ workdir }}/.env"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644