- name: Setup agent configurations
  hosts: agents
  become: yes


  tasks:
    - name: Set config
      template: 
        src: ../templates/.env.agents.j2
        dest: "{{ workdir }}/.env"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644