- name: Setup common backend configurations
  hosts: agents
  become: yes
  vars_files:
    - "../vars/nodes.yml"


  tasks:
    - name: Create directory
      file:
        path: "/srv"
        state: directory

    - name: Clone repository
      git:
        repo: https://github.com/Rock-n-Block/zabbix-monitoring.git
        dest: "{{ agent_workdir }}"

    - name: Set config
      template: 
        src: ../templates/ducatuscoin.conf.j2
        dest: "{{ agent_workdir }}/ducatuscoin.conf"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644
        
    