- name: Setup common backend configurations
  hosts: all
  become: yes
  vars_files:
    - "../vars/nodes.yml"


  tasks:
    - name: Create directory
      file:
        path: "/srv"
        state: directory

    - name: Clone repository
      git:
        repo: https://github.com/Rock-n-Block/zabbix-monitoring.git
        dest: "{{ agent_workdir }}"


        
    